# Generated by Django 2.1.dev20180403030529 on 2018-04-18 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20180326_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchtitle',
            name='research_resources',
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='research_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=''),
            preserve_default=False,
        ),
    ]
