# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-21 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_researchtitle_research_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchtitle',
            name='research_date',
            field=models.IntegerField(null=''),
        ),
    ]
